[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-arg=-sUSE_SDL=2",
    "-C", "link-arg=-sUSE_SDL_IMAGE=2",
    "-C", "link-arg=-sSDL2_IMAGE_FORMATS=['png']",
    "-C", "link-arg=-sMIN_WEBGL_VERSION=2",
    "-C", "link-arg=-sMAX_WEBGL_VERSION=2",
    "-C", "link-arg=-sDISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=0",
    "-C", "link-arg=-sSTACK_SIZE=4194304",
    "-C", "link-arg=-sINITIAL_HEAP=128mb",
]
