[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-arg=-sUSE_SDL=2",
    "-C", "link-arg=-sMIN_WEBGL_VERSION=2",
    "-C", "link-arg=-sMAX_WEBGL_VERSION=2",
    "-C", "link-arg=-sSTACK_SIZE=4194304",
    "-C", "link-arg=-sINITIAL_HEAP=128mb",
]
